#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name

pandoc appoggiatura.md -s --natbib -o appoggiatura.tex

pdflatex appoggiatura.tex
bibtex appoggiatura.aux
pdflatex appoggiatura.tex
pdflatex appoggiatura.tex
rm -f *.{log,aux,nav,out,snm,toc,blg,bbl}
rm -f appoggiatura.tex

