#!/bin/bash

# -s        =>  create standalone file (in this case report.tex latex file)
# --toc     =>  create table of contents
# --natbib  =>  use the natbib package in latex
# -o        =>  output file name

pandoc prelude.md -s -o prelude.tex #--natbib

pdflatex prelude.tex
bibtex prelude.aux
pdflatex prelude.tex
pdflatex prelude.tex
rm -f *.{log,aux,nav,out,snm,toc,blg,bbl}
rm -f prelude.tex

